allowBuilds:
  unrs-resolver: false
minimumReleaseAgeExclude:
  - knip@6.17.1
overrides:
  '@babel/core': ^7.29.6
  '@istanbuljs/load-nyc-config>js-yaml': ^4.2.0
  anymatch>picomatch: ~2.3.2
  istanbul-lib-processinfo>uuid: ~14.0.0
  micromatch>picomatch: ~2.3.2
  mocha>diff: ~8.0.3
  mocha>js-yaml: ^4.2.0
  mocha>serialize-javascript: ~7.0.5
  ts-node>diff: ~4.0.4
  vite: ^8.0.16
