allowBuilds:
  unrs-resolver: false
overrides:
  '@babel/core': ^7.29.7
  '@istanbuljs/load-nyc-config>js-yaml': ^4.3.1
  brace-expansion@1: ~1.1.18
  brace-expansion@2: ~2.1.4
  brace-expansion@5: ~5.0.9
  anymatch>picomatch: ~2.3.2
  istanbul-lib-processinfo>uuid: ~14.0.1
  micromatch>picomatch: ~2.3.2
  mocha>diff: ~8.0.3
  mocha>js-yaml: ^4.3.1
  mocha>serialize-javascript: ~7.1.0
  ts-node>diff: ~4.0.4
  vite: ^8.2.1
