name: CI - tests and coverage
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
    paths:
      - '*.js'
      - '*.ts'
      - '*.json'
      - 'pnpm-lock.yaml'
      - 'test/*'
      - 'src/*'
      - 'src/**/*'
  pull_request:
    paths:
      - '!*.MD'
jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node: [ '20', '22' ]
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v6
    - uses: pnpm/action-setup@v5
      with:
        version: 10.33.2
        run_install: false
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node }}
        cache: pnpm
    - run: pnpm install --frozen-lockfile
    - run: pnpm run test
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: pnpm/action-setup@v5
      with:
        version: 10.33.2
        run_install: false
    - uses: actions/setup-node@v6
      with:
        node-version: '22'
        cache: pnpm
    - run: pnpm install --frozen-lockfile
    - run: pnpm run nyc
    - uses: codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info
        fail_ci_if_error: true
