name: CI - tests and coverage
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
    paths:
      - '*.js'
      - '*.ts'
      - '*.json'
      - 'test/*'
      - 'src/*'
      - 'src/**/*'
  pull_request:
    paths:
      - '!*.MD'
jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node: [ '20', '22' ]
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci
    - run: npm run test
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: npm ci
    - run: npm run coverage-report
    - uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info
        fail_ci_if_error: true
